task1 : task1.c
	gcc -std=c99 -Wall -pedantic -o task1 task1.c -lg2 -lm
task2 : task2.c
	gcc -std=c99 -Wall -pedantic -o task2 task2.c -lg2 -lm
task3 : task3.c
	gcc -std=c99 -Wall -pedantic -o task3 task3.c -lg2 -lm
